name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'epic/**'
      - 'support/**'
    paths:
      - '.github/workflows/format.yml'
      - '**.rs'
      - '**.toml'
      - '**.ts'
      - '**.js'
      - '**.json'

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      # we use nightly to get access to advanced format capabilities
      - name: Setup Rust
        uses: './.github/actions/rust/rust-setup'
        with:
          toolchain: nightly
          os: ${{ runner.os }}
          job: ${{ github.job }}
          components: rustfmt

      - name: Install cargo-license-template
        run: cargo install cargo-license-template

      - name: Install dprint
        run: npm install -g dprint
        #run: cargo install dprint # installing from source is slow, ~5 minutes

      - name: core fmt check
        run: cargo +nightly fmt --all -- --check

      - name: wasm fmt check
        run: cargo +nightly fmt --manifest-path ./bindings/wasm/Cargo.toml --all -- --check

      - name: Cargo.toml fmt check
        run:
          dprint check

      - name: cargo-license-template check
        run: cargo +nightly license-template --template .license_template --ignore .license_template_ignore --verbose
