name: Rust Create Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release Rust under (e.g. `1.2.3`)'
        required: true
      release-type:
        description: Create a `main` or a pre-release. If anything other then `main` is selected, a postfix and auto-incrementing number will be added automatically (e.g. `1.2.3-dev.x`)'
        type: choice
        required: true
        options: 
        - alpha
        - beta
        - rc
        - dev
        - main

jobs:
  create-dev-release-pr:
    if: github.event.inputs.release-type != 'main'
    # owner/repository of workflow has to be static, see https://github.community/t/env-variables-in-uses/17466
    uses: iotaledger/identity.rs/.github/workflows/shared-create-dev-release-pr.yml@main
    with:
      tag-prefix: v
      tag-postfix: -${{ github.event.inputs.release-type }}.
      tag-base: ${{ github.event.inputs.version }}
      main-tag-regex: ^v[0-9]+\.[0-9]+\.[0-9]+$
      changelog-config-path: ./.github/.github_changelog_generator
      release-target: rust
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  create-main-release-pr:
    if: github.event.inputs.release-type == 'main'
    # owner/repository of workflow has to be static, see https://github.community/t/env-variables-in-uses/17466
    uses: iotaledger/identity.rs/.github/workflows/shared-create-main-release-pr.yml@main
    with:
      tag-prefix: v
      tag-base: ${{ github.event.inputs.version }}
      main-tag-regex: ^v[0-9]+\.[0-9]+\.[0-9]+$
      changelog-config-path: ./.github/.github_changelog_generator
      release-target: rust
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}