[package]
name = "proc_typescript"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
license = "Apache-2.0"
publish = false
repository = "https://github.com/iotaledger/identity.rs"
description = "Annotate structs as TypeScript interfaces for wasm-bindgen."

[lib]
name = "proc_typescript"
proc-macro = true

[dependencies]
darling = { version = "0.14.0", default-features = false, features = ["suggestions"] }
proc-macro2 = { version = "1.0", default-features = false }
quote = { version = "1.0", default-features = false }
syn = { version = "1.0", default-features = false, features = ["parsing"] }
