[package]
name = "identity_storage"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["iota", "storage", "identity", "kms"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true
description = "Abstractions over storage for cryptographic keys used in DID Documents"

[dependencies]
async-trait = { version = "0.1.64", default-features = false }
futures = { version = "0.3.27", default-features = false, features = ["async-await"] }
identity_core = { version = "=1.0.0", path = "../identity_core", default-features = false }
identity_credential = { version = "=1.0.0", path = "../identity_credential", default-features = false, features = ["credential", "presentation"] }
identity_did = { version = "=1.0.0", path = "../identity_did", default-features = false }
identity_document = { version = "=1.0.0", path = "../identity_document", default-features = false }
identity_iota_core = { version = "=1.0.0", path = "../identity_iota_core", default-features = false, optional = true }
identity_verification = { version = "=1.0.0", path = "../identity_verification", default_features = false }
iota-crypto = { version = "0.23", default-features = false, features = ["ed25519"], optional = true }
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"], optional = true }
seahash = { version = "4.1.0", default_features = false }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { version = "1.29.0", default-features = false, features = ["macros", "sync"], optional = true }

[dev-dependencies]
identity_credential = { version = "=1.0.0", path = "../identity_credential", features = ["revocation-bitmap"] }
identity_eddsa_verifier = { version = "=1.0.0", path = "../identity_eddsa_verifier", default-features = false, features = ["ed25519"] }
once_cell = { version = "1.18", default-features = false }
tokio = { version = "1.29.0", default-features = false, features = ["macros", "sync", "rt"] }

[features]
default = ["iota-document", "memstore"]
# Exposes in-memory implementations of the storage traits intended exclusively for testing.
memstore = ["dep:tokio", "dep:rand", "dep:iota-crypto"]
# Enables `Send` + `Sync` bounds for the storage traits.
send-sync-storage = []
# Implements the JwkStorageDocumentExt trait for IotaDocument
iota-document = ["dep:identity_iota_core"]
