name: 'publish-wasm'
description: 'Publishes Wasm bindings to npm'
inputs:
  tag:
    description: 'Which npm tag to publish under e.g. `dev`, will default to `latest`'
    required: false
  npm-token:
    description: 'used for authenticating towards npm'
    required: true
  input-artifact-name:
    description: "Name used for the input Wasm build artifact"
    required: true
  dry-run:
    description: "'true' = only log potential result; 'false' = publish'"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Download bindings/wasm artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.input-artifact-name }}
        path: bindings/wasm

    - name: Publish WASM bindings to NPM
      shell: sh
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
      working-directory: bindings/wasm
      # will publish 'latest' tag if no tag is passed
      run: |
        echo "dry-run: '${{ inputs.dry-run }}'"
        echo "tag: '${{ inputs.tag }}'"
        npm publish $(if [ "${{ inputs.dry-run }}" != "false" ]; then echo --dry-run; fi) $(if [ ${{ inputs.tag }} != '' ]; then echo --tag ${{ inputs.tag }}; fi) --access public
