blank_issues_enabled: false
contact_links:
  - name: Official IOTA Discord
    url: https://discord.iota.org/
    about: "Contact the maintainers by joining the #identity channel on the IOTA Discord."
