name: Wasm publish to npm

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish Wasm under (e.g. e.g. `dev`, will default to `latest`)'
        required: true
      branch:
        description: 'Branch to run publish from'
        required: true
      dry-run:
        description: 'Run in dry-run mode'
        type: boolean
        required: false
        default: true

jobs:

  build-wasm: 
    # owner/repository of workflow has to be static, see https://github.community/t/env-variables-in-uses/17466
    uses: iotaledger/identity.rs/.github/workflows/shared-build-wasm.yml@main
    with:
      ref: ${{ github.event.inputs.branch }}
      output-artifact-name: identity-wasm-bindings-build

  release-wasm:
    runs-on: ubuntu-latest
    needs: [build-wasm]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Release to npm
        uses: './.github/actions/publish/publish-wasm'
        with:
          dry-run: ${{ github.event.inputs.dry-run }}
          input-artifact-name: identity-wasm-bindings-build
          npm-token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
