[package]
name = "identity_verification"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Verification data types and functionality for identity.rs"

[dependencies]
identity_core = { version = "=1.0.0", path = "./../identity_core", default-features = false }
identity_did = { version = "=1.0.0", path = "./../identity_did", default-features = false }
identity_jose = { version = "=1.0.0", path = "./../identity_jose", default-features = false }
serde.workspace = true
strum.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
