name: 'setup-sccache'
description: 'Setup sccache.'
inputs:
  os:
    description: 'OS of the runner, used for sccache installation and start.'
    required: true
runs:
  using: "composite"
  steps:

    - name: Install sccache (macos-latest)
      if: inputs.os == 'macos-latest'
      shell: bash
      run: |
        brew update --preinstall
        brew install sccache

    - name: Install sccache (ubuntu-latest)
      if: inputs.os == 'ubuntu-latest'
      shell: bash
      run: |
        SCCACHE_DOWNLOAD_LINK=https://github.com/mozilla/sccache/releases/download
        SCCACHE_VERSION=v0.2.15
        SCCACHE_PREFIX="sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl"
        SCCACHE_TAR="${SCCACHE_PREFIX}.tar.gz"
        DOWNLOAD_LINK="${SCCACHE_DOWNLOAD_LINK}/${SCCACHE_VERSION}/${SCCACHE_TAR}"
        curl -L "${DOWNLOAD_LINK}" --output ${SCCACHE_TAR}
        echo "$(curl -L ${DOWNLOAD_LINK}.sha256)  ${SCCACHE_TAR}" | shasum -a 256 --check --status
        tar xzf ${SCCACHE_TAR}
        BIN_DIR="$HOME/.local/bin"
        mkdir -p ${BIN_DIR}
        mv -f ${SCCACHE_PREFIX}/sccache ${BIN_DIR}/sccache
        chmod a+x "${BIN_DIR}/sccache"
        echo ${BIN_DIR} >> $GITHUB_PATH

    - name: Install sccache (windows-latest)
      if: inputs.os == 'windows-latest'
      shell: pwsh
      run: |
        choco install sccache

    - name: Start sccache
      shell: bash
      run: |
        sccache --start-server
        sccache -s
